export interface DemoProduct {
  name: string;
  category: string;
  price: number;
  costPrice: number;
  stock: number;
}

export const DEMO_STAFF = [
  { name: 'Nguyễn Minh Anh', email: 'minhanh@cuahang.com' },
  { name: 'Trần Quốc Bảo', email: 'quocbao@cuahang.com' },
  { name: 'Lê Thu Hà', email: 'thuha@cuahang.com' },
  { name: 'Phạm Gia Huy', email: 'giahuy@cuahang.com' },
  { name: 'Võ Ngọc Lan', email: 'ngoclan@cuahang.com' },
  { name: 'Đặng Hoàng Nam', email: 'hoangnam@cuahang.com' },
];

export const DEMO_PRODUCTS: DemoProduct[] = [
  {
    name: 'Coca-Cola lon 330ml',
    category: 'Nước giải khát',
    price: 12000,
    costPrice: 8500,
    stock: 220,
  },
  {
    name: 'Pepsi lon 330ml',
    category: 'Nước giải khát',
    price: 12000,
    costPrice: 8200,
    stock: 210,
  },
  {
    name: '7Up lon 330ml',
    category: 'Nước giải khát',
    price: 12000,
    costPrice: 8200,
    stock: 180,
  },
  {
    name: 'Red Bull lon 250ml',
    category: 'Nước giải khát',
    price: 18000,
    costPrice: 13500,
    stock: 160,
  },
  {
    name: 'Trà xanh C2 455ml',
    category: 'Nước giải khát',
    price: 11000,
    costPrice: 7500,
    stock: 190,
  },
  {
    name: 'Trà Ô Long Tea Plus 455ml',
    category: 'Nước giải khát',
    price: 12000,
    costPrice: 8200,
    stock: 175,
  },
  {
    name: 'Nước suối Lavie 500ml',
    category: 'Nước giải khát',
    price: 7000,
    costPrice: 4200,
    stock: 260,
  },
  {
    name: 'Nước cam Twister 320ml',
    category: 'Nước giải khát',
    price: 13000,
    costPrice: 9000,
    stock: 150,
  },

  {
    name: 'Bánh Oreo vani 133g',
    category: 'Bánh kẹo & Snack',
    price: 19000,
    costPrice: 14500,
    stock: 130,
  },
  {
    name: 'Bánh ChocoPie hộp 6 cái',
    category: 'Bánh kẹo & Snack',
    price: 32000,
    costPrice: 25500,
    stock: 105,
  },
  {
    name: 'Bánh AFC vị rau 200g',
    category: 'Bánh kẹo & Snack',
    price: 28000,
    costPrice: 22000,
    stock: 110,
  },
  {
    name: 'Snack Oishi tôm cay 40g',
    category: 'Bánh kẹo & Snack',
    price: 8000,
    costPrice: 5200,
    stock: 180,
  },
  {
    name: 'Khoai tây Lay’s vị tự nhiên 52g',
    category: 'Bánh kẹo & Snack',
    price: 12000,
    costPrice: 8500,
    stock: 145,
  },
  {
    name: 'Socola KitKat 35g',
    category: 'Bánh kẹo & Snack',
    price: 16000,
    costPrice: 12000,
    stock: 95,
  },
  {
    name: 'Kẹo Mentos bạc hà',
    category: 'Bánh kẹo & Snack',
    price: 10000,
    costPrice: 6800,
    stock: 125,
  },

  {
    name: 'Mì Hảo Hảo tôm chua cay',
    category: 'Mì, cháo & Thực phẩm nhanh',
    price: 5000,
    costPrice: 3500,
    stock: 300,
  },
  {
    name: 'Mì Omachi sườn hầm ngũ quả',
    category: 'Mì, cháo & Thực phẩm nhanh',
    price: 9000,
    costPrice: 6500,
    stock: 190,
  },
  {
    name: 'Mì Kokomi 90 tôm chua cay',
    category: 'Mì, cháo & Thực phẩm nhanh',
    price: 5000,
    costPrice: 3400,
    stock: 240,
  },
  {
    name: 'Mì ly Modern lẩu Thái',
    category: 'Mì, cháo & Thực phẩm nhanh',
    price: 11000,
    costPrice: 7800,
    stock: 150,
  },
  {
    name: 'Cháo Gấu Đỏ thịt bằm',
    category: 'Mì, cháo & Thực phẩm nhanh',
    price: 5000,
    costPrice: 3300,
    stock: 170,
  },
  {
    name: 'Phở bò Vifon gói 65g',
    category: 'Mì, cháo & Thực phẩm nhanh',
    price: 8000,
    costPrice: 5600,
    stock: 135,
  },

  {
    name: 'Sữa tươi Vinamilk có đường 180ml',
    category: 'Sữa & Sản phẩm từ sữa',
    price: 9000,
    costPrice: 6800,
    stock: 180,
  },
  {
    name: 'Sữa tươi TH true MILK 180ml',
    category: 'Sữa & Sản phẩm từ sữa',
    price: 10000,
    costPrice: 7400,
    stock: 165,
  },
  {
    name: 'Sữa Dutch Lady socola 180ml',
    category: 'Sữa & Sản phẩm từ sữa',
    price: 9000,
    costPrice: 6600,
    stock: 150,
  },
  {
    name: 'Milo hộp 180ml',
    category: 'Sữa & Sản phẩm từ sữa',
    price: 10000,
    costPrice: 7500,
    stock: 175,
  },
  {
    name: 'Sữa chua Vinamilk có đường lốc 4',
    category: 'Sữa & Sản phẩm từ sữa',
    price: 30000,
    costPrice: 24500,
    stock: 90,
  },
  {
    name: 'Sữa đặc Ông Thọ đỏ 380g',
    category: 'Sữa & Sản phẩm từ sữa',
    price: 27000,
    costPrice: 22000,
    stock: 85,
  },

  {
    name: 'Gạo thơm Jasmine túi 5kg',
    category: 'Thực phẩm thiết yếu',
    price: 115000,
    costPrice: 97000,
    stock: 65,
  },
  {
    name: 'Dầu ăn Simply 1 lít',
    category: 'Thực phẩm thiết yếu',
    price: 58000,
    costPrice: 49000,
    stock: 80,
  },
  {
    name: 'Nước mắm Nam Ngư 500ml',
    category: 'Thực phẩm thiết yếu',
    price: 35000,
    costPrice: 28500,
    stock: 95,
  },
  {
    name: 'Đường tinh luyện Biên Hòa 1kg',
    category: 'Thực phẩm thiết yếu',
    price: 26000,
    costPrice: 22000,
    stock: 110,
  },
  {
    name: 'Muối i-ốt Bạc Liêu 500g',
    category: 'Thực phẩm thiết yếu',
    price: 8000,
    costPrice: 5200,
    stock: 125,
  },
  {
    name: 'Hạt nêm Knorr thịt thăn 400g',
    category: 'Thực phẩm thiết yếu',
    price: 42000,
    costPrice: 35000,
    stock: 75,
  },

  {
    name: 'Kem đánh răng P/S 180g',
    category: 'Chăm sóc cá nhân',
    price: 36000,
    costPrice: 29000,
    stock: 85,
  },
  {
    name: 'Bàn chải Colgate Flex Clean',
    category: 'Chăm sóc cá nhân',
    price: 18000,
    costPrice: 12500,
    stock: 100,
  },
  {
    name: 'Dầu gội Clear Men 630g',
    category: 'Chăm sóc cá nhân',
    price: 168000,
    costPrice: 142000,
    stock: 45,
  },
  {
    name: 'Sữa tắm Lifebuoy 800g',
    category: 'Chăm sóc cá nhân',
    price: 145000,
    costPrice: 121000,
    stock: 48,
  },
  {
    name: 'Xà phòng Lifebuoy 90g',
    category: 'Chăm sóc cá nhân',
    price: 14000,
    costPrice: 9800,
    stock: 115,
  },
  {
    name: 'Khăn giấy ướt Bobby 30 tờ',
    category: 'Chăm sóc cá nhân',
    price: 28000,
    costPrice: 21000,
    stock: 78,
  },

  {
    name: 'Nước rửa chén Sunlight 750g',
    category: 'Đồ dùng gia đình',
    price: 32000,
    costPrice: 26000,
    stock: 90,
  },
  {
    name: 'Nước lau sàn Gift 1 lít',
    category: 'Đồ dùng gia đình',
    price: 36000,
    costPrice: 29000,
    stock: 75,
  },
  {
    name: 'Bột giặt OMO 800g',
    category: 'Đồ dùng gia đình',
    price: 44000,
    costPrice: 36500,
    stock: 82,
  },
  {
    name: 'Nước xả Comfort 800ml',
    category: 'Đồ dùng gia đình',
    price: 52000,
    costPrice: 43000,
    stock: 68,
  },
  {
    name: 'Giấy vệ sinh Pulppy 10 cuộn',
    category: 'Đồ dùng gia đình',
    price: 68000,
    costPrice: 56000,
    stock: 60,
  },
  {
    name: 'Túi rác tự hủy cuộn 3 màu',
    category: 'Đồ dùng gia đình',
    price: 25000,
    costPrice: 17500,
    stock: 88,
  },

  {
    name: 'Xúc xích tiệt trùng CP gói 5 cây',
    category: 'Đồ đông lạnh',
    price: 26000,
    costPrice: 20500,
    stock: 95,
  },
  {
    name: 'Cá viên chiên 500g',
    category: 'Đồ đông lạnh',
    price: 52000,
    costPrice: 43000,
    stock: 58,
  },
  {
    name: 'Bò viên 500g',
    category: 'Đồ đông lạnh',
    price: 78000,
    costPrice: 65000,
    stock: 52,
  },
  {
    name: 'Há cảo mini 500g',
    category: 'Đồ đông lạnh',
    price: 68000,
    costPrice: 56000,
    stock: 55,
  },
  {
    name: 'Khoai tây đông lạnh 500g',
    category: 'Đồ đông lạnh',
    price: 46000,
    costPrice: 37500,
    stock: 62,
  },

  {
    name: 'Pin Panasonic AA vỉ 4 viên',
    category: 'Văn phòng & Tiện ích',
    price: 36000,
    costPrice: 27000,
    stock: 70,
  },
  {
    name: 'Bút bi Thiên Long TL-027',
    category: 'Văn phòng & Tiện ích',
    price: 5000,
    costPrice: 2800,
    stock: 140,
  },
  {
    name: 'Khẩu trang y tế hộp 50 cái',
    category: 'Văn phòng & Tiện ích',
    price: 38000,
    costPrice: 29000,
    stock: 75,
  },
  {
    name: 'Băng keo trong 4.8cm',
    category: 'Văn phòng & Tiện ích',
    price: 15000,
    costPrice: 9500,
    stock: 90,
  },
  {
    name: 'Bật lửa gas mini',
    category: 'Văn phòng & Tiện ích',
    price: 7000,
    costPrice: 4000,
    stock: 105,
  },
];
